- name: Install go
  ansible.builtin.shell: |
    source ~/.zprofile
    mise install go@latest 2>&1
  args:
    executable: /bin/bash
  register: go_install
  changed_when: "'installed' in go_install.stdout"

- name: Install useful go binaries
  ansible.builtin.shell: |
    source ~/.zprofile
    go install {{ item }}
  args:
    executable: /bin/bash
  loop: "{{ go_binaries }}"
  changed_when: false
