- name: Gather facts
  hosts: localhost
  gather_facts: false
  become: false
  tags: always
  tasks:
    - name: Run setup module
      ansible.builtin.setup:

- name: Privileged tasks
  hosts: localhost
  gather_facts: false
  become: true
  tags: priv
  tasks:
    - name: Update system packages
      ansible.builtin.import_role:
        name: update
      tags: update

    - name: Manage additional packages
      ansible.builtin.import_role:
        name: packages
      tags: packages

    - name: Install Brave browser
      ansible.builtin.import_role:
        name: brave
      tags: brave

    - name: Install Docker
      ansible.builtin.import_role:
        name: docker
      tags: docker

    - name: Change default shell
      ansible.builtin.import_role:
        name: shell
      tags: shell

- name: Non-Privileged tasks
  hosts: localhost
  gather_facts: false
  become: false
  tags: nonpriv
  tasks:
    - name: Setup GNU Stow
      ansible.builtin.import_role:
        name: stow
      tags: stow

    - name: Install Rust
      ansible.builtin.import_role:
        name: rust
      tags: rust

    - name: Setup Mise
      ansible.builtin.import_role:
        name: mise
      tags: mise

    - name: Install Go
      ansible.builtin.import_role:
        name: go
      tags: go

    - name: Install Node
      ansible.builtin.import_role:
        name: node
      tags: node

    - name: Install python
      ansible.builtin.import_role:
        name: python
      tags: python

- name: Instructions
  hosts: all
  gather_facts: false
  become: false
  tags: always
  tasks:
    - name: End message
      ansible.builtin.debug:
        msg: "Please either restart or logout to load the changes"
