- name: Facts
  hosts: localhost
  gather_facts: false
  become: false
  tags: always
  tasks:
    - name: Gather facts manually
      ansible.builtin.setup:

- name: Privileged tasks
  hosts: localhost
  gather_facts: false
  become: true
  tags: priv
  tasks:
    - name: Update system packages
      ansible.builtin.import_role:
        name: update
      tags: update

    - name: Manage additional packages
      ansible.builtin.import_role:
        name: packages
      tags: packages

    - name: Change default shell
      ansible.builtin.import_role:
        name: shell
      tags: shell

- name: Non-Privileged tasks
  hosts: localhost
  gather_facts: false
  become: false
  tags: nonpriv
  tasks:
    - name: Setup dev tools
      ansible.builtin.import_role:
        name: tools
      tags: tools

- name: Instructions
  hosts: all
  gather_facts: false
  become: false
  tags: always
  tasks:
    - name: End message
      ansible.builtin.debug:
        msg: "Please either restart or logout to load the changes"
