- name: Install python
  ansible.builtin.shell: |
    source ~/.zprofile
    mise install python@latest 2>&1
  args:
    executable: /bin/bash
  register: python_install
  changed_when: "'installed' in python_install.stdout"

- name: Install Python packages
  ansible.builtin.command: "pipx install {{ item }}"
  loop: "{{ python_pip_packages }}"
  changed_when: false
