[general]
import = ["theme.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 50000
multiplier = 3

[window]
decorations = "None"
opacity = 1.0
startup_mode = "Maximized"
class = { general = "Alacritty", instance = "Alacritty" }
padding = { x = 5, y = 5 }

[font]
size = 14.0
normal = { family = "JetBrainsMono NFM", style = "SemiBold" }
bold = { family = "JetBrainsMono NFM", style = "ExtraBold" }
italic = { family = "JetBrainsMono NFM", style = "SemiBold Italic" }

[cursor]
unfocused_hollow = true
style = { blinking = "On", shape = "Block" }
vi_mode_style = { blinking = "On", shape = "Block" }
