live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 50000
multiplier = 3

[window]
decorations = "None"
opacity = 1.0

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold Italic"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Block"

[colors]
draw_bold_text_with_bright_colors = true

# carbonfox colors
[colors.primary]
background = "#161616"
foreground = "#f2f4f8"
dim_foreground = "#b6b8bb"
bright_foreground = "#f9fbff"

[colors.vi_mode_cursor]
text = "#f2f4f8"
cursor = "#33b1ff"

[colors.search.matches]
foreground = "#f2f4f8"
background = "#525253"

[colors.search.focused_match]
foreground = "#f2f4f8"
background = "#3ddbd9"

[colors.footer_bar]
foreground = "#f2f4f8"
background = "#353535"

[colors.hints.start]
foreground = "#f2f4f8"
background = "#3ddbd9"

[colors.hints.end]
foreground = "#f2f4f8"
background = "#353535"

[colors.selection]
text = "#f2f4f8"
background = "#2a2a2a"

[colors.normal]
black = "#282828"
red = "#ee5396"
green = "#25be6a"
yellow = "#ffe97b"
blue = "#78a9ff"
magenta = "#be95ff"
cyan = "#33b1ff"
white = "#dfdfe0"

[colors.bright]
black = "#393939"
red = "#ee5396"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
magenta = "#ff7eb6"
cyan = "#3ddbd9"
white = "#ffffff"

[colors.dim]
black = "#222222"
red = "#ca4780"
green = "#1fa25a"
yellow = "#ffe97b"
blue = "#6690d9"
magenta = "#a27fd9"
cyan = "#2b96d9"
white = "#bebebe"

[[colors.indexed_colors]]
index = 16
color = "#3ddbd9"

[[colors.indexed_colors]]
index = 17
color = "#ff7eb6"
