import = ["~/.config/alacritty/theme.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 50000
multiplier = 3

[window]
decorations = "None"
opacity = 1.0
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold Italic"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Block"
